{% set name = "flet" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flet-{{ version }}.tar.gz
  sha256: 5d65e47ab26c32ec35ea06cbab93a6db5441d8c098a870277788a7e1e261b737

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - flet = flet.cli.cli:main

requirements:
  host:
    - poetry-core
    - pip
    - python >=3.7
  run:
    - flet-core ==0.4.0
    - httpx >=0.23.3,<0.24.0
    - oauthlib >=3.2.2,<4.0.0
    - packaging >=23.0,<24.0
    - python >=3.7,<4.0
    - typing_extensions >=4.4.0,<5.0.0
    - watchdog >=2.2.1,<3.0.0
    - websocket-client >=1.4.2,<2.0.0
    - websocket >=10.4,<11.0

test:
  imports:
    - flet
  commands:
    - pip check
    - flet --help
  requires:
    - pip

about:
  home: https://github.com/flet-dev/flet
  dev_url: https://github.com/flet-dev/flet/tree/main/sdk/python
  doc_url: https://flet.dev/docs/
  summary: Flet for Python - easily build interactive multi-platform apps in Python
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
