{% set name = "flet" %}
{% set version = "0.1.63" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flet-{{ version }}.tar.gz
  sha256: c3cf1c4a8e06814d150419d6b31617ebae2e8acc001aaa86f5c586239b2dc392

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - flet = flet.flet:main

requirements:
  host:
    - pdm-pep517
    - pip
    - python >=3.7
  run:
    - beartype >=0.9.1
    - cryptography >=38.0.1
    - oauthlib >=3.2.0
    - python >=3.7
    - repath >=0.9.0
    - requests >=2.28.1
    - typing_extensions
    - watchdog >=2.1.9
    - websocket-client >=1.2.1

test:
  source_files:
    - tests
  imports:
    - flet
  commands:
    - pip check
    - flet --help
    - pytest -vvv --capture=tee-sys tests
  requires:
    - pip
    - pytest >=6.1.2

about:
  home: https://github.com/flet-dev/flet
  dev_url: https://github.com/flet-dev/flet/tree/main/sdk/python
  doc_url: https://flet.dev/docs/
  summary: Flet for Python - easily build interactive multi-platform apps in Python
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
