{% set name = "flet" %}
{% set version = "0.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flet-{{ version }}.tar.gz
  sha256: 6507857cf622eb4f7a6ad58a0b67d85f7da80a3969e661ab45d24b988c027c3d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - flet = flet.cli.cli:main

requirements:
  host:
    - pip
    - poetry-core
    - python >=3.7,<4.0
  run:
    - flet-core =={{ version }}
    - httpx >=0.23.3,<0.24.0
    - oauthlib >=3.2.2,<4.0.0
    - packaging >=23.0,<24.0
    - python >=3.7,<4.0
    - typing_extensions >=4.4.0,<5.0.0
    - watchdog >=2.2.1,<3.0.0
    - websockets >=10.4,<11.0
    - websocket-client >=1.4.2,<2.0.0

test:
  imports:
    - flet
  commands:
    - pip check
    - flet --help
  requires:
    - pip

about:
  home: https://github.com/flet-dev/flet
  dev_url: https://github.com/flet-dev/flet/tree/main/sdk/python
  doc_url: https://flet.dev/docs/
  summary: Flet for Python - easily build interactive multi-platform apps in Python
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
