{% set name = "flet" %}
{% set version = "0.1.53" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flet-{{ version }}.tar.gz
  sha256: a1b2f534f6f75fc93d436764b537cfecc1960a94d3ec482826a423ef4dac4b71

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pdm-pep517
    - pip
    - python >=3.7
  run:
    - beartype >=0.9.1
    - python >=3.7
    - repath >=0.9.0
    - typing_extensions
    - websocket-client >=1.2.1

test:
  imports:
    - flet
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/flet-dev/flet
  dev_url: https://github.com/flet-dev/flet/tree/main/sdk/python
  doc_url: https://flet.dev/docs/
  summary: Flet for Python - easily build interactive multi-platform apps in Python
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
