{% set name = "flet" %}
{% set version = "0.21.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flet-{{ version }}.tar.gz
  sha256: fe8f7d9b57a9c5d909fb4d549262b54954f4bb17645ef1cf16ad56bd4e31df01

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - flet = flet.cli.cli:main

requirements:
  host:
    - pip
    - poetry-core
    - python
  run:
    - python >=3.8,<4.0
    - flet-runtime =={{ version }}
    - watchdog >=3.0.0,<4.0.0
    - packaging >=23.1,<24.0
    - qrcode >=7.4.2,<8.0.0
    - copier >=8.2.0,<9.0.0
    - cookiecutter >=2.4.0,<3.0.0
    - fastapi >=0.109.2,<0.110.0
    - uvicorn >=0.27.1,<0.28.0

test:
  imports:
    - flet
  commands:
    - pip check
    - flet --help
  requires:
    - pip

about:
  home: https://github.com/flet-dev/flet
  dev_url: https://github.com/flet-dev/flet/tree/main/sdk/python
  doc_url: https://flet.dev/docs/
  summary: Flet for Python - easily build interactive multi-platform apps in Python
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
