{% set name = "flet" %}
{% set version = "0.20.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flet-{{ version }}.tar.gz
  sha256: dcb85023f8637a74f11bfd4364fff39f6cecd34ad3e41be20c04186f6bee7013

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - flet = flet.cli.cli:main

requirements:
  host:
    - pip
    - poetry-core
    - python >=3.7,<4.0
  run:
    - cookiecutter >=2.4.0,<3.0.0
    - copier >=8.2.0,<9.0.0
    - flet-runtime =={{ version }}
    - packaging >=23.1,<24.0
    - python >=3.7,<4.0
    - qrcode >=7.4.2,<8.0.0
    - typing_extensions >=4.6.2,<5.0.0
    - watchdog >=3.0.0,<4.0.0
    - websockets >=11.0.3,<12.0.0
    - websocket-client >=1.5.2,<2.0.0

test:
  imports:
    - flet
  commands:
    - pip check
    - flet --help
  requires:
    - pip

about:
  home: https://github.com/flet-dev/flet
  dev_url: https://github.com/flet-dev/flet/tree/main/sdk/python
  doc_url: https://flet.dev/docs/
  summary: Flet for Python - easily build interactive multi-platform apps in Python
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
