{% set name = "flet" %}
{% set version = "0.1.54" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flet-{{ version }}.tar.gz
  sha256: f40716c719deff3c1149b2994943e2b5d6cc41b071c0002d902b3278360d374f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - flet = flet.flet:main

requirements:
  host:
    - pdm-pep517
    - pip
    - python >=3.7
  run:
    - beartype >=0.9.1
    - python >=3.7
    - repath >=0.9.0
    - typing_extensions
    - watchdog >=2.1.9
    - websocket-client >=1.2.1

test:
  imports:
    - flet
  commands:
    - pip check
    - flet --help
  requires:
    - pip

about:
  home: https://github.com/flet-dev/flet
  dev_url: https://github.com/flet-dev/flet/tree/main/sdk/python
  doc_url: https://flet.dev/docs/
  summary: Flet for Python - easily build interactive multi-platform apps in Python
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
