{% set name = "flet" %}
{% set version = "0.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flet-{{ version }}.tar.gz
  sha256: 3a0cb817dfdb7926f7182a703ec37ef21b15ae84681d34a88ea83ee5e5f07112

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - flet = flet.cli.cli:main

requirements:
  host:
    - pip
    - poetry-core
    - python >=3.7,<4.0
  run:
    - copier >=8.0.0,<9.0.0
    - flet-runtime =={{ version }}
    - packaging >=23.1,<24.0
    - python >=3.7,<4.0
    - pydantic <2
    - qrcode >=7.4.2,<8.0.0
    - typing_extensions >=4.6.2,<5.0.0
    - watchdog >=3.0.0,<4.0.0
    - websockets >=11.0.3,<12.0.0
    - websocket-client >=1.5.2,<2.0.0

test:
  imports:
    - flet
  commands:
    - pip check
    - flet --help
  requires:
    - pip

about:
  home: https://github.com/flet-dev/flet
  dev_url: https://github.com/flet-dev/flet/tree/main/sdk/python
  doc_url: https://flet.dev/docs/
  summary: Flet for Python - easily build interactive multi-platform apps in Python
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
