{% set name = "flet" %}
{% set version = "0.80.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/flet-{{ version }}.tar.gz
  sha256: f2d4607d2e5d1e55286799c2a4c8188386b21641ac56481384d0fc58ec171cbd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - flet = flet.cli.cli:main

requirements:
  host:
    - pip
    - poetry-core
    - python {{ python_min }}
  run:
    - python >={{ python_min }},<4.0
    - flet-runtime =={{ version }}
    - watchdog >=4.0.0,<5.0.0
    - packaging >=23.1,<24.0
    - qrcode >=7.4.2,<8.0.0
    - cookiecutter >=2.6.0,<3.0.0
    - fastapi >=0,<1
    - uvicorn-standard >=0,<1

test:
  imports:
    - flet
  commands:
    - pip check
    - flet --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://flet.dev
  dev_url: https://github.com/flet-dev/flet
  doc_url: https://flet.dev/docs/
  summary: Flet for Python - easily build interactive multi-platform apps in Python
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
