schema_version: 1

context:
  name: flet
  version: "0.80.4"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/flet-${{ version }}.tar.gz
  sha256: 4e821d32c8941bb9443063ce71332451fccd10e9d7e0ad29a839c5e780f20360

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - flet = flet.cli:main

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}
    - oauthlib >=3.2.2
    - httpx >=0.28.1
    - repath >=0.9.0
    - msgpack-python >=1.1.0
    - typing-extensions

tests:
  - python:
      imports:
        - flet
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
        - flet-cli
    script:
      - flet --help

about:
  summary: Flet for Python - easily build interactive multi-platform apps in Python
  license: Apache-2.0
  license_file:
    - LICENSE
  homepage: https://flet.dev
  repository: https://github.com/flet-dev/flet
  documentation: https://flet.dev/docs/

extra:
  recipe-maintainers:
    - thewchan
